/**
 * Clipboard utilities for copying text
 */

/**
 * Copy text to clipboard with fallback for older browsers
 */
export async function copyToClipboard(text: string): Promise<boolean> {
	try {
		// Modern clipboard API
		if (navigator.clipboard && navigator.clipboard.writeText) {
			await navigator.clipboard.writeText(text);
			return true;
		}

		// Fallback for older browsers
		const textArea = document.createElement('textarea');
		textArea.value = text;
		textArea.style.position = 'fixed';
		textArea.style.left = '-999999px';
		textArea.style.top = '-999999px';
		document.body.appendChild(textArea);
		textArea.focus();
		textArea.select();

		try {
			const successful = document.execCommand('copy');
			document.body.removeChild(textArea);
			return successful;
		} catch (err) {
			document.body.removeChild(textArea);
			return false;
		}
	} catch (err) {
		console.error('Failed to copy:', err);
		return false;
	}
}

/**
 * Format prescription results for clipboard
 */
export function formatPrescriptionForClipboard(result: any): string {
	const { prescription, sigParsed, calculation, ndcs, recommendation } = result;

	let output = '=== PRESCRIPTION CALCULATION ===\n\n';

	// Prescription Info
	output += '📋 PRESCRIPTION:\n';
	output += `Drug: ${prescription.drug}\n`;
	output += `RxCUI: ${prescription.rxcui}\n`;
	output += `Directions: ${prescription.sig}\n`;
	output += `Quantity: ${prescription.quantity}\n\n`;

	// Dosing Info
	output += '💊 DOSING:\n';
	output += `Units per Dose: ${sigParsed.unitsPerDose}\n`;
	output += `Frequency: ${sigParsed.frequency}x daily\n`;
	output += `Total Daily Dose: ${sigParsed.totalDailyDose}\n`;
	output += `PRN: ${sigParsed.prn ? 'Yes' : 'No'}\n\n`;

	// Calculation
	output += '📊 CALCULATION:\n';
	output += `Days Supply: ${calculation.daysSupply} days\n`;
	output += `Quantity Needed: ${calculation.quantityNeeded}\n\n`;

	// Package Recommendation
	if (recommendation && recommendation.packages.length > 0) {
		output += '📦 RECOMMENDED PACKAGES:\n';
		recommendation.packages.forEach((pkg: any, idx: number) => {
			const ndcInfo = ndcs.find((n: any) => n.ndc === pkg.ndc);
			output += `${idx + 1}. NDC: ${pkg.ndc}\n`;
			output += `   Quantity: ${pkg.quantity} bottle(s) × ${pkg.totalUnits / pkg.quantity} units\n`;
			output += `   Total: ${pkg.totalUnits} units\n`;
			if (ndcInfo) {
				output += `   Manufacturer: ${ndcInfo.labelerName}\n`;
			}
		});

		output += `\nTotal Dispensed: ${recommendation.totalDispensed} units\n`;
		if (recommendation.overfill > 0) {
			output += `Overfill: ${recommendation.overfill} units (${recommendation.overfillPercentage.toFixed(1)}%)\n`;
		}
	}

	output += `\n--- Generated by PharmaMax ---`;

	return output;
}

/**
 * Format NDC information for clipboard
 */
export function formatNDCForClipboard(ndc: string, labelerName: string, packageSize: number): string {
	return `NDC: ${ndc}\nManufacturer: ${labelerName}\nPackage Size: ${packageSize}`;
}
