<script lang="ts">
	import { copyToClipboard } from '$lib/utils/clipboard';
	import DrugInteractionChecker from './DrugInteractionChecker.svelte';
	import ChatAssistant from './ChatAssistant.svelte';

	export let result: any;

	const { prescription, sigParsed, calculation, ndcs, recommendation } = result;

	let copySuccess = false;
	let copyingNDC: string | null = null;

	async function copyFullResults() {
		let output = '=== PRESCRIPTION CALCULATION ===\n\n';

		output += '📋 PRESCRIPTION:\n';
		output += `Drug: ${prescription.drugName}\n`;
		output += `RxCUI: ${prescription.rxcui}\n`;
		output += `Directions: ${prescription.sig}\n`;
		output += `Days Supply: ${prescription.daysSupply} days\n\n`;

		output += '💊 DOSING:\n';
		output += `Dose: ${sigParsed.dosePerAdministration} per administration\n`;
		output += `Frequency: ${sigParsed.frequencyPerDay}x daily\n`;
		output += `Route: ${sigParsed.route}\n`;
		output += `Total Daily: ${sigParsed.totalDailyDose} ${calculation.unit}/day\n\n`;

		output += '📊 QUANTITY:\n';
		output += `Total Needed: ${calculation.totalQuantityNeeded} ${calculation.unit}\n\n`;

		if (recommendation.packages.length > 0) {
			output += '📦 RECOMMENDED PACKAGES:\n';
			recommendation.packages.forEach((pkg: any, idx: number) => {
				output += `${idx + 1}. NDC ${pkg.ndc}: ${pkg.quantity} package(s) = ${pkg.totalUnits} units\n`;
			});
			output += `\nTotal Dispensed: ${recommendation.totalDispensed} ${calculation.unit}\n`;
			if (recommendation.overfill > 0) {
				output += `Overfill: ${recommendation.overfill} units (${recommendation.overfillPercentage.toFixed(1)}%)\n`;
			}
		}

		output += `\n--- Generated by PharmaMax ---`;

		const success = await copyToClipboard(output);
		if (success) {
			copySuccess = true;
			setTimeout(() => (copySuccess = false), 2000);
		}
	}

	async function copyNDC(ndc: any) {
		const text = `NDC: ${ndc.ndc}\nPackage Size: ${ndc.packageSize} ${ndc.packageType}\nManufacturer: ${ndc.labelerName}\nStatus: ${ndc.isActive ? 'Active' : 'Inactive'}`;
		const success = await copyToClipboard(text);
		if (success) {
			copyingNDC = ndc.ndc;
			setTimeout(() => (copyingNDC = null), 1500);
		}
	}

	function printResults() {
		window.print();
	}
</script>

<div class="space-y-6">
	<!-- Action Buttons -->
	<div class="flex justify-end gap-3 print:hidden">
		<button
			on:click={printResults}
			class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors flex items-center gap-2"
		>
			<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"
				/>
			</svg>
			Print
		</button>

		<button
			on:click={copyFullResults}
			class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
		>
			{#if copySuccess}
				<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
					<path
						fill-rule="evenodd"
						d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
						clip-rule="evenodd"
					/>
				</svg>
				Copied!
			{:else}
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
					/>
				</svg>
				Copy All Results
			{/if}
		</button>
	</div>

	<!-- Prescription Summary -->
	<div class="bg-white border border-blue-200 rounded-lg p-6">
		<h3 class="text-xl font-semibold text-blue-900 mb-4">Prescription Summary</h3>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
			<div>
				<p class="text-sm font-medium text-gray-600">Drug</p>
				<p class="text-lg text-gray-900">{prescription.drugName}</p>
				<p class="text-sm text-gray-500">RxCUI: {prescription.rxcui}</p>
			</div>
			<div>
				<p class="text-sm font-medium text-gray-600">Days' Supply</p>
				<p class="text-lg text-gray-900">{prescription.daysSupply} days</p>
			</div>
		</div>
		<div class="mt-4">
			<p class="text-sm font-medium text-gray-600">SIG</p>
			<p class="text-gray-900">{prescription.sig}</p>
		</div>
	</div>

	<!-- Parsed SIG Details -->
	<div class="bg-blue-50 border border-blue-200 rounded-lg p-6">
		<h3 class="text-xl font-semibold text-blue-900 mb-4">Parsed Instructions</h3>
		<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
			<div>
				<p class="text-sm font-medium text-gray-600">Dose</p>
				<p class="text-2xl font-bold text-blue-600">{sigParsed.dosePerAdministration}</p>
				<p class="text-sm text-gray-500">per administration</p>
			</div>
			<div>
				<p class="text-sm font-medium text-gray-600">Frequency</p>
				<p class="text-2xl font-bold text-blue-600">{sigParsed.frequencyPerDay}x</p>
				<p class="text-sm text-gray-500">per day</p>
			</div>
			<div>
				<p class="text-sm font-medium text-gray-600">Route</p>
				<p class="text-lg font-semibold text-gray-900">{sigParsed.route}</p>
			</div>
			<div>
				<p class="text-sm font-medium text-gray-600">Daily Total</p>
				<p class="text-2xl font-bold text-green-600">{sigParsed.totalDailyDose}</p>
				<p class="text-sm text-gray-500">{calculation.unit}/day</p>
			</div>
		</div>
	</div>

	<!-- Total Quantity Needed -->
	<div class="bg-green-50 border border-green-200 rounded-lg p-6">
		<h3 class="text-xl font-semibold text-green-900 mb-2">Total Quantity Needed</h3>
		<p class="text-4xl font-bold text-green-600">
			{calculation.totalQuantityNeeded}
			<span class="text-2xl text-gray-600">{calculation.unit}</span>
		</p>
		<p class="text-sm text-gray-600 mt-2">
			({sigParsed.totalDailyDose} {calculation.unit}/day × {prescription.daysSupply} days)
		</p>
	</div>

	<!-- Available NDCs -->
	<div class="bg-white border border-gray-200 rounded-lg p-6">
		<h3 class="text-xl font-semibold text-gray-900 mb-4">Available NDCs</h3>
		<div class="overflow-x-auto">
			<table class="min-w-full divide-y divide-gray-200">
				<thead class="bg-gray-50">
					<tr>
						<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							NDC
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Package Size
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Type
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Status
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Labeler
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider print:hidden">
							Actions
						</th>
					</tr>
				</thead>
				<tbody class="bg-white divide-y divide-gray-200">
					{#each ndcs as ndc}
						<tr class:bg-gray-50={!ndc.isActive}>
							<td class="px-4 py-3 text-sm font-mono text-gray-900">{ndc.ndc}</td>
							<td class="px-4 py-3 text-sm text-gray-900 font-semibold">{ndc.packageSize}</td>
							<td class="px-4 py-3 text-sm text-gray-600 capitalize">{ndc.packageType}</td>
							<td class="px-4 py-3 text-sm">
								{#if ndc.isActive}
									<span
										class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800"
									>
										Active
									</span>
								{:else}
									<span
										class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800"
									>
										Inactive
									</span>
								{/if}
							</td>
							<td class="px-4 py-3 text-sm text-gray-600">{ndc.labelerName}</td>
							<td class="px-4 py-3 text-sm print:hidden">
								<button
									on:click={() => copyNDC(ndc)}
									class="text-blue-600 hover:text-blue-800 transition-colors flex items-center gap-1"
									title="Copy NDC info"
								>
									{#if copyingNDC === ndc.ndc}
										<svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
											<path
												fill-rule="evenodd"
												d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
												clip-rule="evenodd"
											/>
										</svg>
									{:else}
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
											/>
										</svg>
									{/if}
								</button>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</div>

	<!-- Drug Interaction Checker -->
	<DrugInteractionChecker
		currentDrug={prescription.drugName}
		currentRxcui={prescription.rxcui}
	/>

	<!-- AI Chat Assistant -->
	<ChatAssistant
		prescriptionContext={{
			drugName: prescription.drugName,
			rxcui: prescription.rxcui,
			sig: prescription.sig,
			daysSupply: prescription.daysSupply,
			totalQuantity: calculation.totalQuantityNeeded,
			unit: calculation.unit
		}}
	/>

	<!-- Packaging Recommendation -->
	<div class="bg-purple-50 border border-purple-200 rounded-lg p-6">
		<h3 class="text-xl font-semibold text-purple-900 mb-4">Recommended Package Combination</h3>

		{#if recommendation.warnings.length > 0}
			<div class="mb-4 bg-yellow-50 border border-yellow-200 rounded p-3">
				<p class="text-sm font-medium text-yellow-800">Warnings:</p>
				<ul class="list-disc list-inside text-sm text-yellow-700 mt-1">
					{#each recommendation.warnings as warning}
						<li>{warning}</li>
					{/each}
				</ul>
			</div>
		{/if}

		{#if recommendation.packages.length > 0}
			<div class="space-y-3">
				{#each recommendation.packages as pkg}
					<div class="bg-white rounded-lg p-4 border border-purple-200">
						<div class="flex justify-between items-start">
							<div>
								<p class="font-mono text-sm text-gray-600">NDC: {pkg.ndc}</p>
								<p class="text-lg font-semibold text-gray-900 mt-1">
									Quantity: {pkg.quantity} package{pkg.quantity > 1 ? 's' : ''}
								</p>
							</div>
							<div class="text-right">
								<p class="text-2xl font-bold text-purple-600">{pkg.totalUnits}</p>
								<p class="text-sm text-gray-500">{calculation.unit} total</p>
							</div>
						</div>
					</div>
				{/each}

				<div class="border-t border-purple-200 pt-4 mt-4">
					<div class="grid grid-cols-2 gap-4">
						<div>
							<p class="text-sm font-medium text-gray-600">Total Dispensed</p>
							<p class="text-2xl font-bold text-purple-600">
								{recommendation.totalDispensed}
								{calculation.unit}
							</p>
						</div>
						<div>
							<p class="text-sm font-medium text-gray-600">Overfill</p>
							<p class="text-2xl font-bold text-gray-600">
								{recommendation.overfill}
								{calculation.unit}
							</p>
							<p class="text-sm text-gray-500">
								({recommendation.overfillPercentage.toFixed(1)}%)
							</p>
						</div>
					</div>
				</div>
			</div>
		{:else}
			<p class="text-gray-600">No package recommendations available.</p>
		{/if}
	</div>
</div>
