<script lang="ts">
	import { copyToClipboard } from '$lib/utils/clipboard';
	import DrugInteractionChecker from './DrugInteractionChecker.svelte';
	import ChatAssistant from './ChatAssistant.svelte';
	import CalculationBreakdown from './CalculationBreakdown.svelte';
	import PackageVisualizer from './PackageVisualizer.svelte';
	import RefillCalculator from './RefillCalculator.svelte';
	import PrescriptionLabel from './PrescriptionLabel.svelte';
	import StockWarning from './StockWarning.svelte';

	export let result: any;

	const { prescription, sigParsed, calculation, ndcs, recommendation } = result;

	let copySuccess = false;
	let copyingNDC: string | null = null;

	async function copyFullResults() {
		let output = '=== PRESCRIPTION CALCULATION ===\n\n';

		output += '📋 PRESCRIPTION:\n';
		output += `Drug: ${prescription.drugName}\n`;
		output += `RxCUI: ${prescription.rxcui}\n`;
		output += `Directions: ${prescription.sig}\n`;
		output += `Days Supply: ${prescription.daysSupply} days\n\n`;

		output += '💊 DOSING:\n';
		output += `Dosage Form: ${sigParsed.dosageForm}\n`;
		output += `Dose: ${sigParsed.dosePerAdministration} ${sigParsed.unit} per administration\n`;
		output += `Frequency: ${sigParsed.frequencyPerDay}x daily\n`;
		output += `Route: ${sigParsed.route}\n`;
		output += `Total Daily: ${sigParsed.totalDailyDose} ${calculation.unit}/day\n\n`;

		output += '📊 QUANTITY:\n';
		output += `Total Needed: ${calculation.totalQuantityNeeded} ${calculation.unit}\n\n`;

		if (recommendation.packages.length > 0) {
			output += '📦 RECOMMENDED PACKAGES:\n';
			recommendation.packages.forEach((pkg: any, idx: number) => {
				output += `${idx + 1}. NDC ${pkg.ndc}: ${pkg.quantity} package(s) = ${pkg.totalUnits} units\n`;
			});
			output += `\nTotal Dispensed: ${recommendation.totalDispensed} ${calculation.unit}\n`;
			if (recommendation.overfill > 0) {
				output += `Overfill: ${recommendation.overfill} units (${recommendation.overfillPercentage.toFixed(1)}%)\n`;
			}
		}

		output += `\n--- Generated by PharmaMax ---`;

		const success = await copyToClipboard(output);
		if (success) {
			copySuccess = true;
			setTimeout(() => (copySuccess = false), 2000);
		}
	}

	async function copyNDC(ndc: any) {
		const text = `NDC: ${ndc.ndc}\nPackage Size: ${ndc.packageSize} ${ndc.packageType}\nManufacturer: ${ndc.labelerName}\nStatus: ${ndc.isActive ? 'Active' : 'Inactive'}`;
		const success = await copyToClipboard(text);
		if (success) {
			copyingNDC = ndc.ndc;
			setTimeout(() => (copyingNDC = null), 1500);
		}
	}

	function printResults() {
		window.print();
	}

	function exportJSON() {
		const jsonOutput = {
			prescription,
			sigParsed,
			calculation,
			ndcs,
			recommendation,
			timestamp: new Date().toISOString()
		};

		const blob = new Blob([JSON.stringify(jsonOutput, null, 2)], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `prescription-${prescription.rxcui}-${Date.now()}.json`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	}
</script>

<div class="space-y-6">
	<!-- Action Buttons -->
	<div class="flex justify-end gap-3 print:hidden">
		<button
			on:click={exportJSON}
			class="px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
			style="background-color: var(--border-color); color: var(--foreground);"
			title="Export as JSON"
		>
			<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
				/>
			</svg>
			Export JSON
		</button>

		<button
			on:click={printResults}
			class="px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
			style="background-color: var(--border-color); color: var(--foreground);"
		>
			<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"
				/>
			</svg>
			Print
		</button>

		<button
			on:click={copyFullResults}
			class="btn-primary px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
		>
			{#if copySuccess}
				<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
					<path
						fill-rule="evenodd"
						d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
						clip-rule="evenodd"
					/>
				</svg>
				Copied!
			{:else}
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
					/>
				</svg>
				Copy All Results
			{/if}
		</button>
	</div>

	<!-- Notification Banners -->
	{#if ndcs.filter(ndc => !ndc.isActive).length > 0}
		<div class="rounded-lg p-4 flex items-start gap-3 print:hidden" style="background-color: rgba(245, 158, 11, 0.15); border: 1px solid rgba(245, 158, 11, 0.4);">
			<svg class="w-6 h-6 flex-shrink-0 mt-0.5" style="color: #f59e0b;" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
			</svg>
			<div class="flex-1">
				<p class="font-semibold" style="color: #f59e0b;">
					Inactive NDCs Found
				</p>
				<p class="text-sm mt-1" style="color: var(--text-secondary);">
					{ndcs.filter(ndc => !ndc.isActive).length} inactive NDC{ndcs.filter(ndc => !ndc.isActive).length > 1 ? 's' : ''} detected and excluded from recommendations. These NDCs are no longer available from manufacturers and should not be dispensed.
				</p>
			</div>
		</div>
	{/if}

	{#if recommendation.overfillPercentage > 50}
		<div class="rounded-lg p-4 flex items-start gap-3 print:hidden" style="background-color: rgba(239, 68, 68, 0.15); border: 1px solid rgba(239, 68, 68, 0.4);">
			<svg class="w-6 h-6 flex-shrink-0 mt-0.5" style="color: #ef4444;" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
			</svg>
			<div class="flex-1">
				<p class="font-semibold" style="color: #ef4444;">
					High Overfill Warning
				</p>
				<p class="text-sm mt-1" style="color: var(--text-secondary);">
					The recommended package combination results in {recommendation.overfillPercentage.toFixed(1)}% overfill ({recommendation.overfill} extra {calculation.unit}). Consider alternative package sizes or verify with prescriber if available.
				</p>
			</div>
		</div>
	{/if}

	{#if recommendation.packages.length === 0}
		<div class="rounded-lg p-4 flex items-start gap-3 print:hidden" style="background-color: rgba(239, 68, 68, 0.15); border: 1px solid rgba(239, 68, 68, 0.4);">
			<svg class="w-6 h-6 flex-shrink-0 mt-0.5" style="color: #ef4444;" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
			</svg>
			<div class="flex-1">
				<p class="font-semibold" style="color: #ef4444;">
					No Active Packages Available
				</p>
				<p class="text-sm mt-1" style="color: var(--text-secondary);">
					No active NDCs are available to fulfill this prescription. All found NDCs are inactive. Please verify drug name or contact prescriber for alternative medication.
				</p>
			</div>
		</div>
	{/if}

	<!-- Prescription Summary -->
	<div class="card-hover rounded-lg p-6" style="background-color: var(--card-bg); border: 1px solid rgba(16, 185, 129, 0.3);">
		<h3 class="text-xl font-semibold mb-4" style="color: var(--accent);">Prescription Summary</h3>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Drug</p>
				<p class="text-lg" style="color: var(--foreground);">{prescription.drugName}</p>
				<p class="text-sm" style="color: var(--text-muted);">RxCUI: {prescription.rxcui}</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Days' Supply</p>
				<p class="text-lg" style="color: var(--foreground);">{prescription.daysSupply} days</p>
			</div>
		</div>
		<div class="mt-4">
			<p class="text-sm font-medium" style="color: var(--text-secondary);">SIG</p>
			<p style="color: var(--foreground);">{prescription.sig}</p>
		</div>
	</div>

	<!-- Parsed SIG Details -->
	<div class="card-hover rounded-lg p-6" style="background-color: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3);">
		<h3 class="text-xl font-semibold mb-4 flex items-center gap-2" style="color: var(--accent);">
			Parsed Instructions
			{#if sigParsed.dosageForm === 'liquid'}
				<span class="text-sm px-2 py-1 rounded" style="background-color: rgba(59, 130, 246, 0.2); color: #3b82f6;">Liquid</span>
			{:else if sigParsed.dosageForm === 'insulin'}
				<span class="text-sm px-2 py-1 rounded" style="background-color: rgba(168, 85, 247, 0.2); color: #a855f7;">Insulin</span>
			{:else if sigParsed.dosageForm === 'inhaler'}
				<span class="text-sm px-2 py-1 rounded" style="background-color: rgba(14, 165, 233, 0.2); color: #0ea5e9;">Inhaler</span>
			{:else if sigParsed.dosageForm === 'oral_solid'}
				<span class="text-sm px-2 py-1 rounded" style="background-color: rgba(16, 185, 129, 0.2); color: #10b981;">Oral Solid</span>
			{/if}
		</h3>
		<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Dose</p>
				<p class="text-2xl font-bold" style="color: var(--accent);">{sigParsed.dosePerAdministration}</p>
				<p class="text-sm" style="color: var(--text-muted);">{sigParsed.unit} per administration</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Frequency</p>
				<p class="text-2xl font-bold" style="color: var(--accent);">{sigParsed.frequencyPerDay}x</p>
				<p class="text-sm" style="color: var(--text-muted);">per day</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Route</p>
				<p class="text-lg font-semibold" style="color: var(--foreground);">{sigParsed.route}</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Daily Total</p>
				<p class="text-2xl font-bold" style="color: #10b981;">{sigParsed.totalDailyDose}</p>
				<p class="text-sm" style="color: var(--text-muted);">{calculation.unit}/day</p>
			</div>
		</div>
	</div>

	<!-- Calculation Breakdown -->
	<CalculationBreakdown
		{prescription}
		{sigParsed}
		{calculation}
		{ndcs}
		{recommendation}
	/>

	<!-- Total Quantity Needed -->
	<div class="card-hover rounded-lg p-6" style="background-color: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3);">
		<h3 class="text-xl font-semibold mb-2" style="color: #10b981;">Total Quantity Needed</h3>
		<p class="text-4xl font-bold" style="color: #10b981;">
			{calculation.totalQuantityNeeded}
			<span class="text-2xl" style="color: var(--text-secondary);">{calculation.unit}</span>
		</p>
		<p class="text-sm mt-2" style="color: var(--text-secondary);">
			({sigParsed.totalDailyDose} {calculation.unit}/day × {prescription.daysSupply} days)
		</p>

		<!-- Special dosage form notes -->
		{#if sigParsed.dosageForm === 'liquid'}
			<div class="mt-4 p-3 rounded" style="background-color: rgba(59, 130, 246, 0.1); border: 1px solid rgba(59, 130, 246, 0.3);">
				<p class="text-xs font-semibold" style="color: #3b82f6;">📋 Liquid Medication Note:</p>
				<p class="text-xs mt-1" style="color: var(--text-secondary);">Verify bottle size matches total mL needed. Common sizes: 120mL, 240mL, 473mL (16oz).</p>
			</div>
		{:else if sigParsed.dosageForm === 'insulin'}
			<div class="mt-4 p-3 rounded" style="background-color: rgba(168, 85, 247, 0.1); border: 1px solid rgba(168, 85, 247, 0.3);">
				<p class="text-xs font-semibold" style="color: #a855f7;">💉 Insulin Note:</p>
				<p class="text-xs mt-1" style="color: var(--text-secondary);">Standard vials contain 1000 units (10mL). Pens vary by type (typically 300 units per pen).</p>
			</div>
		{:else if sigParsed.dosageForm === 'inhaler'}
			<div class="mt-4 p-3 rounded" style="background-color: rgba(14, 165, 233, 0.1); border: 1px solid rgba(14, 165, 233, 0.3);">
				<p class="text-xs font-semibold" style="color: #0ea5e9;">🌬️ Inhaler Note:</p>
				<p class="text-xs mt-1" style="color: var(--text-secondary);">Most inhalers contain 60, 90, 120, or 200 doses. Check product labeling for exact dose count.</p>
			</div>
		{/if}
	</div>

	<!-- Available NDCs -->
	<div class="card-hover rounded-lg p-6" style="background-color: var(--card-bg); border: 1px solid var(--border-color);">
		<h3 class="text-xl font-semibold mb-4" style="color: var(--foreground);">Available NDCs</h3>
		<div class="overflow-x-auto">
			<table class="min-w-full" style="border: 1px solid var(--border-color);">
				<thead style="background-color: var(--background);">
					<tr>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							NDC
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Package Size
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Type
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Status
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Labeler
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider print:hidden" style="color: var(--text-muted);">
							Actions
						</th>
					</tr>
				</thead>
				<tbody style="background-color: var(--card-bg);">
					{#each ndcs as ndc}
						<tr style="{ndc.isActive ? '' : 'opacity: 0.5;'} border-top: 1px solid var(--border-color);">
							<td class="px-4 py-3 text-sm font-mono" style="color: var(--foreground);">{ndc.ndc}</td>
							<td class="px-4 py-3 text-sm font-semibold" style="color: var(--foreground);">{ndc.packageSize}</td>
							<td class="px-4 py-3 text-sm capitalize" style="color: var(--text-secondary);">{ndc.packageType}</td>
							<td class="px-4 py-3 text-sm">
								{#if ndc.isActive}
									<span
										class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
										style="background-color: rgba(16, 185, 129, 0.2); color: #10b981;"
									>
										Active
									</span>
								{:else}
									<span
										class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
										style="background-color: rgba(239, 68, 68, 0.2); color: #ef4444;"
									>
										Inactive
									</span>
								{/if}
							</td>
							<td class="px-4 py-3 text-sm" style="color: var(--text-secondary);">{ndc.labelerName}</td>
							<td class="px-4 py-3 text-sm print:hidden">
								<button
									on:click={() => copyNDC(ndc)}
									class="transition-colors flex items-center gap-1"
									style="color: var(--accent);"
									title="Copy NDC info"
								>
									{#if copyingNDC === ndc.ndc}
										<svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
											<path
												fill-rule="evenodd"
												d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
												clip-rule="evenodd"
											/>
										</svg>
									{:else}
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
											/>
										</svg>
									{/if}
								</button>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</div>

	<!-- Package Options Visualizer -->
	<PackageVisualizer
		totalNeeded={calculation.totalQuantityNeeded}
		unit={calculation.unit}
		{ndcs}
		currentRecommendation={recommendation}
	/>

	<!-- Refill Date Calculator -->
	<RefillCalculator
		daysSupply={prescription.daysSupply}
		drugName={prescription.drugName}
	/>

	<!-- Prescription Label -->
	<PrescriptionLabel
		prescription={{
			drugName: prescription.drugName,
			sig: prescription.sig,
			daysSupply: prescription.daysSupply,
			calculation,
			recommendation
		}}
	/>

	<!-- Drug Interaction Checker -->
	<DrugInteractionChecker
		currentDrug={prescription.drugName}
		currentRxcui={prescription.rxcui}
	/>

	<!-- AI Chat Assistant -->
	<ChatAssistant
		prescriptionContext={{
			drugName: prescription.drugName,
			rxcui: prescription.rxcui,
			sig: prescription.sig,
			daysSupply: prescription.daysSupply,
			totalQuantity: calculation.totalQuantityNeeded,
			unit: calculation.unit
		}}
	/>

	<!-- Packaging Recommendation -->
	<div class="card-hover rounded-lg p-6" style="background-color: rgba(168, 85, 247, 0.1); border: 1px solid rgba(168, 85, 247, 0.3);">
		<h3 class="text-xl font-semibold mb-4" style="color: #a855f7;">Recommended Package Combination</h3>

		{#if recommendation.warnings.length > 0}
			<div class="mb-4 rounded p-3" style="background-color: rgba(245, 158, 11, 0.1); border: 1px solid rgba(245, 158, 11, 0.3);">
				<p class="text-sm font-medium" style="color: #f59e0b;">Warnings:</p>
				<ul class="list-disc list-inside text-sm mt-1" style="color: var(--text-secondary);">
					{#each recommendation.warnings as warning}
						<li>{warning}</li>
					{/each}
				</ul>
			</div>
		{/if}

		{#if recommendation.packages.length > 0}
			<div class="space-y-3">
				{#each recommendation.packages as pkg}
					<div class="rounded-lg p-4" style="background-color: var(--card-bg); border: 1px solid rgba(168, 85, 247, 0.3);">
						<div class="flex justify-between items-start">
							<div>
								<p class="font-mono text-sm" style="color: var(--text-secondary);">NDC: {pkg.ndc}</p>
								<p class="text-lg font-semibold mt-1" style="color: var(--foreground);">
									Quantity: {pkg.quantity} package{pkg.quantity > 1 ? 's' : ''}
								</p>
							</div>
							<div class="text-right">
								<p class="text-2xl font-bold" style="color: #a855f7;">{pkg.totalUnits}</p>
								<p class="text-sm" style="color: var(--text-muted);">{calculation.unit} total</p>
							</div>
						</div>
						<!-- Stock Warning Integration -->
						<StockWarning ndc={pkg.ndc} drugName={prescription.drugName} />
					</div>
				{/each}

				<div class="pt-4 mt-4" style="border-top: 1px solid rgba(168, 85, 247, 0.3);">
					<div class="grid grid-cols-2 gap-4">
						<div>
							<p class="text-sm font-medium" style="color: var(--text-secondary);">Total Dispensed</p>
							<p class="text-2xl font-bold" style="color: #a855f7;">
								{recommendation.totalDispensed}
								{calculation.unit}
							</p>
						</div>
						<div>
							<p class="text-sm font-medium" style="color: var(--text-secondary);">Overfill</p>
							<p class="text-2xl font-bold" style="color: var(--text-secondary);">
								{recommendation.overfill}
								{calculation.unit}
							</p>
							<p class="text-sm" style="color: var(--text-muted);">
								({recommendation.overfillPercentage.toFixed(1)}%)
							</p>
						</div>
					</div>
				</div>
			</div>
		{:else}
			<p style="color: var(--text-secondary);">No package recommendations available.</p>
		{/if}
	</div>
</div>
