<script lang="ts">
	import { copyToClipboard } from '$lib/utils/clipboard';
	import DrugInteractionChecker from './DrugInteractionChecker.svelte';
	import ChatAssistant from './ChatAssistant.svelte';

	export let result: any;

	const { prescription, sigParsed, calculation, ndcs, recommendation } = result;

	let copySuccess = false;
	let copyingNDC: string | null = null;

	async function copyFullResults() {
		let output = '=== PRESCRIPTION CALCULATION ===\n\n';

		output += '📋 PRESCRIPTION:\n';
		output += `Drug: ${prescription.drugName}\n`;
		output += `RxCUI: ${prescription.rxcui}\n`;
		output += `Directions: ${prescription.sig}\n`;
		output += `Days Supply: ${prescription.daysSupply} days\n\n`;

		output += '💊 DOSING:\n';
		output += `Dose: ${sigParsed.dosePerAdministration} per administration\n`;
		output += `Frequency: ${sigParsed.frequencyPerDay}x daily\n`;
		output += `Route: ${sigParsed.route}\n`;
		output += `Total Daily: ${sigParsed.totalDailyDose} ${calculation.unit}/day\n\n`;

		output += '📊 QUANTITY:\n';
		output += `Total Needed: ${calculation.totalQuantityNeeded} ${calculation.unit}\n\n`;

		if (recommendation.packages.length > 0) {
			output += '📦 RECOMMENDED PACKAGES:\n';
			recommendation.packages.forEach((pkg: any, idx: number) => {
				output += `${idx + 1}. NDC ${pkg.ndc}: ${pkg.quantity} package(s) = ${pkg.totalUnits} units\n`;
			});
			output += `\nTotal Dispensed: ${recommendation.totalDispensed} ${calculation.unit}\n`;
			if (recommendation.overfill > 0) {
				output += `Overfill: ${recommendation.overfill} units (${recommendation.overfillPercentage.toFixed(1)}%)\n`;
			}
		}

		output += `\n--- Generated by PharmaMax ---`;

		const success = await copyToClipboard(output);
		if (success) {
			copySuccess = true;
			setTimeout(() => (copySuccess = false), 2000);
		}
	}

	async function copyNDC(ndc: any) {
		const text = `NDC: ${ndc.ndc}\nPackage Size: ${ndc.packageSize} ${ndc.packageType}\nManufacturer: ${ndc.labelerName}\nStatus: ${ndc.isActive ? 'Active' : 'Inactive'}`;
		const success = await copyToClipboard(text);
		if (success) {
			copyingNDC = ndc.ndc;
			setTimeout(() => (copyingNDC = null), 1500);
		}
	}

	function printResults() {
		window.print();
	}
</script>

<div class="space-y-6">
	<!-- Action Buttons -->
	<div class="flex justify-end gap-3 print:hidden">
		<button
			on:click={printResults}
			class="px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
			style="background-color: var(--border-color); color: var(--foreground);"
		>
			<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"
				/>
			</svg>
			Print
		</button>

		<button
			on:click={copyFullResults}
			class="btn-primary px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
		>
			{#if copySuccess}
				<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
					<path
						fill-rule="evenodd"
						d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
						clip-rule="evenodd"
					/>
				</svg>
				Copied!
			{:else}
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
					/>
				</svg>
				Copy All Results
			{/if}
		</button>
	</div>

	<!-- Prescription Summary -->
	<div class="card-hover rounded-lg p-6" style="background-color: var(--card-bg); border: 1px solid rgba(16, 185, 129, 0.3);">
		<h3 class="text-xl font-semibold mb-4" style="color: var(--accent);">Prescription Summary</h3>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Drug</p>
				<p class="text-lg" style="color: var(--foreground);">{prescription.drugName}</p>
				<p class="text-sm" style="color: var(--text-muted);">RxCUI: {prescription.rxcui}</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Days' Supply</p>
				<p class="text-lg" style="color: var(--foreground);">{prescription.daysSupply} days</p>
			</div>
		</div>
		<div class="mt-4">
			<p class="text-sm font-medium" style="color: var(--text-secondary);">SIG</p>
			<p style="color: var(--foreground);">{prescription.sig}</p>
		</div>
	</div>

	<!-- Parsed SIG Details -->
	<div class="card-hover rounded-lg p-6" style="background-color: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3);">
		<h3 class="text-xl font-semibold mb-4" style="color: var(--accent);">Parsed Instructions</h3>
		<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Dose</p>
				<p class="text-2xl font-bold" style="color: var(--accent);">{sigParsed.dosePerAdministration}</p>
				<p class="text-sm" style="color: var(--text-muted);">per administration</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Frequency</p>
				<p class="text-2xl font-bold" style="color: var(--accent);">{sigParsed.frequencyPerDay}x</p>
				<p class="text-sm" style="color: var(--text-muted);">per day</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Route</p>
				<p class="text-lg font-semibold" style="color: var(--foreground);">{sigParsed.route}</p>
			</div>
			<div>
				<p class="text-sm font-medium" style="color: var(--text-secondary);">Daily Total</p>
				<p class="text-2xl font-bold" style="color: #10b981;">{sigParsed.totalDailyDose}</p>
				<p class="text-sm" style="color: var(--text-muted);">{calculation.unit}/day</p>
			</div>
		</div>
	</div>

	<!-- Total Quantity Needed -->
	<div class="card-hover rounded-lg p-6" style="background-color: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3);">
		<h3 class="text-xl font-semibold mb-2" style="color: #10b981;">Total Quantity Needed</h3>
		<p class="text-4xl font-bold" style="color: #10b981;">
			{calculation.totalQuantityNeeded}
			<span class="text-2xl" style="color: var(--text-secondary);">{calculation.unit}</span>
		</p>
		<p class="text-sm mt-2" style="color: var(--text-secondary);">
			({sigParsed.totalDailyDose} {calculation.unit}/day × {prescription.daysSupply} days)
		</p>
	</div>

	<!-- Available NDCs -->
	<div class="card-hover rounded-lg p-6" style="background-color: var(--card-bg); border: 1px solid var(--border-color);">
		<h3 class="text-xl font-semibold mb-4" style="color: var(--foreground);">Available NDCs</h3>
		<div class="overflow-x-auto">
			<table class="min-w-full" style="border: 1px solid var(--border-color);">
				<thead style="background-color: var(--background);">
					<tr>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							NDC
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Package Size
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Type
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Status
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider" style="color: var(--text-muted);">
							Labeler
						</th>
						<th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider print:hidden" style="color: var(--text-muted);">
							Actions
						</th>
					</tr>
				</thead>
				<tbody style="background-color: var(--card-bg);">
					{#each ndcs as ndc}
						<tr style="{ndc.isActive ? '' : 'opacity: 0.5;'} border-top: 1px solid var(--border-color);">
							<td class="px-4 py-3 text-sm font-mono" style="color: var(--foreground);">{ndc.ndc}</td>
							<td class="px-4 py-3 text-sm font-semibold" style="color: var(--foreground);">{ndc.packageSize}</td>
							<td class="px-4 py-3 text-sm capitalize" style="color: var(--text-secondary);">{ndc.packageType}</td>
							<td class="px-4 py-3 text-sm">
								{#if ndc.isActive}
									<span
										class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
										style="background-color: rgba(16, 185, 129, 0.2); color: #10b981;"
									>
										Active
									</span>
								{:else}
									<span
										class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
										style="background-color: rgba(239, 68, 68, 0.2); color: #ef4444;"
									>
										Inactive
									</span>
								{/if}
							</td>
							<td class="px-4 py-3 text-sm" style="color: var(--text-secondary);">{ndc.labelerName}</td>
							<td class="px-4 py-3 text-sm print:hidden">
								<button
									on:click={() => copyNDC(ndc)}
									class="transition-colors flex items-center gap-1"
									style="color: var(--accent);"
									title="Copy NDC info"
								>
									{#if copyingNDC === ndc.ndc}
										<svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
											<path
												fill-rule="evenodd"
												d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
												clip-rule="evenodd"
											/>
										</svg>
									{:else}
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
											/>
										</svg>
									{/if}
								</button>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</div>

	<!-- Drug Interaction Checker -->
	<DrugInteractionChecker
		currentDrug={prescription.drugName}
		currentRxcui={prescription.rxcui}
	/>

	<!-- AI Chat Assistant -->
	<ChatAssistant
		prescriptionContext={{
			drugName: prescription.drugName,
			rxcui: prescription.rxcui,
			sig: prescription.sig,
			daysSupply: prescription.daysSupply,
			totalQuantity: calculation.totalQuantityNeeded,
			unit: calculation.unit
		}}
	/>

	<!-- Packaging Recommendation -->
	<div class="card-hover rounded-lg p-6" style="background-color: rgba(168, 85, 247, 0.1); border: 1px solid rgba(168, 85, 247, 0.3);">
		<h3 class="text-xl font-semibold mb-4" style="color: #a855f7;">Recommended Package Combination</h3>

		{#if recommendation.warnings.length > 0}
			<div class="mb-4 rounded p-3" style="background-color: rgba(245, 158, 11, 0.1); border: 1px solid rgba(245, 158, 11, 0.3);">
				<p class="text-sm font-medium" style="color: #f59e0b;">Warnings:</p>
				<ul class="list-disc list-inside text-sm mt-1" style="color: var(--text-secondary);">
					{#each recommendation.warnings as warning}
						<li>{warning}</li>
					{/each}
				</ul>
			</div>
		{/if}

		{#if recommendation.packages.length > 0}
			<div class="space-y-3">
				{#each recommendation.packages as pkg}
					<div class="rounded-lg p-4" style="background-color: var(--card-bg); border: 1px solid rgba(168, 85, 247, 0.3);">
						<div class="flex justify-between items-start">
							<div>
								<p class="font-mono text-sm" style="color: var(--text-secondary);">NDC: {pkg.ndc}</p>
								<p class="text-lg font-semibold mt-1" style="color: var(--foreground);">
									Quantity: {pkg.quantity} package{pkg.quantity > 1 ? 's' : ''}
								</p>
							</div>
							<div class="text-right">
								<p class="text-2xl font-bold" style="color: #a855f7;">{pkg.totalUnits}</p>
								<p class="text-sm" style="color: var(--text-muted);">{calculation.unit} total</p>
							</div>
						</div>
					</div>
				{/each}

				<div class="pt-4 mt-4" style="border-top: 1px solid rgba(168, 85, 247, 0.3);">
					<div class="grid grid-cols-2 gap-4">
						<div>
							<p class="text-sm font-medium" style="color: var(--text-secondary);">Total Dispensed</p>
							<p class="text-2xl font-bold" style="color: #a855f7;">
								{recommendation.totalDispensed}
								{calculation.unit}
							</p>
						</div>
						<div>
							<p class="text-sm font-medium" style="color: var(--text-secondary);">Overfill</p>
							<p class="text-2xl font-bold" style="color: var(--text-secondary);">
								{recommendation.overfill}
								{calculation.unit}
							</p>
							<p class="text-sm" style="color: var(--text-muted);">
								({recommendation.overfillPercentage.toFixed(1)}%)
							</p>
						</div>
					</div>
				</div>
			</div>
		{:else}
			<p style="color: var(--text-secondary);">No package recommendations available.</p>
		{/if}
	</div>
</div>
